### ISSUE TITLE
Unable to Reproduce DCASE2019 Task4 challenge results

### ISSUE THREAD

**Issue by udaylunawat** [Kikyo-16/Sound_event_detection#2]
Here's the error log -

```
2020-01-15 07:20:51.994231: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-01-15 07:20:51.998584: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2020-01-15 07:20:51.998641: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: instance-2
2020-01-15 07:20:51.998654: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: instance-2
2020-01-15 07:20:51.998707: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 440.33.1
2020-01-15 07:20:51.998765: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 440.33.1
2020-01-15 07:20:51.998779: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 440.33.1
 INFO - Disentangled feature
 INFO - task name: Lin_ICT_task4
 INFO - PS-model name: sed_with_cATP-DF
 INFO - mode: test
 INFO - semi_supervised: False
 INFO - ensemble results (just a single model)
Traceback (most recent call last):
  File "main.py", line 307, in <module>
    test_models(task_name, sed_model_name, model_weights_list)
  File "main.py", line 202, in test_models
    test(task_name, sed_model_name, model_list[0])
  File "main.py", line 145, in test
    train = trainer.trainer(task_name,model_name,True)
  File "/home/udaylunawat/Sound_event_detection/src/trainer.py", line 76, in __init__
    self.init_data()
  File "/home/udaylunawat/Sound_event_detection/src/trainer.py", line 128, in init_data
    self.data_loader = data.data_loader(conf_dir)
  File "/home/udaylunawat/Sound_event_detection/src/data_loader.py", line 49, in __init__
    self.init_data_conf()
  File "/home/udaylunawat/Sound_event_detection/src/data_loader.py", line 88, in init_data_conf
    assert os.path.exists(f)
AssertionError
```
I've checked the tensorflow-gpu installation & it works.
```
>>> tf.test.is_gpu_available()
2020-01-15 07:20:44.186951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2020-01-15 07:20:44.187094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-15 07:20:44.187108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2020-01-15 07:20:44.187116: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2020-01-15 07:20:44.187209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/device:GPU:0 with 244 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
True
```

Would you also tell me the directory structure for the data/wav and data/feature folder.
Thanks!!

**Comment by Kikyo-16** [comment]
Hi, the folder `data/wav` contains all the audio files published by DCASE2019 Task4 (no any subfolder). Before running `sh scripts/reproduce_Lin_ICT_task4_*.sh` to reproduce the results, you should run `gen_feature-2019.sh` and `gen_label-2019.sh` to generated features and labels.

**Comment by udaylunawat** [comment]
> Hi, the folder `data/wav` contains all the audio files published by DCASE2019 Task4 (no any subfolder). Before running `sh scripts/reproduce_Lin_ICT_task4_*.sh` to reproduce the results, you should run `gen_feature-2019.sh` and `gen_label-2019.sh` to generated features and labels.

The evaluation dataset link seems to be dead. Would it work with missing files?

**Comment by Kikyo-16** [comment]
Sure. Actually, according to the configuration files we provide, the codes only test results with the test set. All you need to do is remove the lines which aim to generate the features and labels of the evaluation set in files `gen_feature-2019.sh` and `gen_label-2019.sh`.

**Comment by udaylunawat** [comment]
Thank you so much for the help @Kikyo-16 .
Why do you think the programs warns "failed call to cuInit: CUDA_ERROR_NO_DEVICE" even when tensorflow-gpu is setup and working?

**Comment by Kikyo-16** [comment]
The line `CUDA_VISIBLE_DEVICES=3` in the script is to specify the visible GPU device. If there is no corresponding GPU device in your machine, it will cast this warning. Of course, you can revise it to change the specified GPU device.

**Comment by ckdals7419** [comment]
Hi, I am also trying to reproduce this model that won first place in DCASE 2019.

Like you answered above, 

I uploaded all the downloaded files to `data/wav`, and finished data preparation by running `gen_feature-2019.sh` and `gen_label-2019.sh`

Then I ran `sh scripts/reproduce_Lin_ICT_task4_*.sh` and an error occurred in the **load_weights function.**

This is error log.

> (venv) changmin@kresnik:~/Sound_event_detection$ sh scripts/reproduce_Lin_ICT_task4_4.sh
> Using TensorFlow backend.
> 2020-01-16 23:23:37.829291: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
>  INFO - Disentangled feature
>  INFO - task name: Lin_ICT_task4
>  INFO - PS-model name: sed_with_cATP-DF
>  INFO - mode: test
>  INFO - semi_supervised: False
>  INFO - decode for model : challenge_results/model_weights/437296/best_model_w.h5
> Traceback (most recent call last):
>   File "main.py", line 309, in <module>
>     test_models(task_name, sed_model_name, model_weights_list)
>   File "main.py", line 210, in test_models
>     at_preds, sed_preds = test(task_name, sed_model_name, model_path)
>   File "main.py", line 149, in test
>     at_preds_out = train.save_at_result(at_preds)       #audio tagging result
>   File "/mnt/sdb1/changmin/Sound_event_detection/src/trainer.py", line 372, in save_at_result
>     preds_out['vali'] = self.save_at('vali', at_preds, is_add = False)
>   File "/mnt/sdb1/changmin/Sound_event_detection/src/trainer.py", line 413, in save_at
>     preds, labels = self.test(mode, 'at', at_preds)
>   File "/mnt/sdb1/changmin/Sound_event_detection/src/trainer.py", line 337, in test
>     mode = mode)
>   File "/mnt/sdb1/changmin/Sound_event_detection/src/model.py", line 596, in get_model
>     model.load_weights(pre_model, by_name = True)
>   File "/home/changmin/venv/lib/python3.6/site-packages/keras/engine/network.py", line 1177, in load_weights
>     reshape=reshape)
>   File "/home/changmin/venv/lib/python3.6/site-packages/keras/engine/saving.py", line 1018, in load_weights_from_hdf5_group_by_name
>     str(weight_values[i].shape) + '.')
> **ValueError: Layer #87 (named "sed_with_cATP-DF_atten_0"), weight <tf.Variable 'sed_with_cATP-DF_atten_0/sed_with_cATP-DF_atten_0_kernel:0' shape=(1, 1, 138) dtype=float32_ref> has shape (1, 1, 138), but the saved weight has shape (1, 1, 137)**.


Previously saved `challenge_results/model_weights/437296/best_model_w.h5`
I just loaded the model, and I'm embarrassed to see this error.

I really want to study using this model. I would be grateful if you could help. thank you : )

**Comment by Kikyo-16** [comment]
Hi, please make sure that the label dir is empty before you run gen_label-2019.py. Or when calculating DF dimenssions, the code will consider all the audio files with labels in the trainning set, which leads to the error.

**Comment by udaylunawat** [comment]
> Hi, I am also trying to reproduce this model that won first place in DCASE 2019.
> 
> Like you answered above,
> 
> I uploaded all the downloaded files to `data/wav`, and finished data preparation by running `gen_feature-2019.sh` and `gen_label-2019.sh`
> 
> Then I ran `sh scripts/reproduce_Lin_ICT_task4_*.sh` and an error occurred in the **load_weights function.**
> 
> This is error log.
> 
> > (venv) changmin@kresnik:~/Sound_event_detection$ sh scripts/reproduce_Lin_ICT_task4_4.sh
> > Using TensorFlow backend.
> > 2020-01-16 23:23:37.829291: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
> > INFO - Disentangled feature
> > INFO - task name: Lin_ICT_task4
> > INFO - PS-model name: sed_with_cATP-DF
> > INFO - mode: test
> > INFO - semi_supervised: False
> > INFO - decode for model : challenge_results/model_weights/437296/best_model_w.h5
> > Traceback (most recent call last):
> > File "main.py", line 309, in 
> > test_models(task_name, sed_model_name, model_weights_list)
> > File "main.py", line 210, in test_models
> > at_preds, sed_preds = test(task_name, sed_model_name, model_path)
> > File "main.py", line 149, in test
> > at_preds_out = train.save_at_result(at_preds)       #audio tagging result
> > File "/mnt/sdb1/changmin/Sound_event_detection/src/trainer.py", line 372, in save_at_result
> > preds_out['vali'] = self.save_at('vali', at_preds, is_add = False)
> > File "/mnt/sdb1/changmin/Sound_event_detection/src/trainer.py", line 413, in save_at
> > preds, labels = self.test(mode, 'at', at_preds)
> > File "/mnt/sdb1/changmin/Sound_event_detection/src/trainer.py", line 337, in test
> > mode = mode)
> > File "/mnt/sdb1/changmin/Sound_event_detection/src/model.py", line 596, in get_model
> > model.load_weights(pre_model, by_name = True)
> > File "/home/changmin/venv/lib/python3.6/site-packages/keras/engine/network.py", line 1177, in load_weights
> > reshape=reshape)
> > File "/home/changmin/venv/lib/python3.6/site-packages/keras/engine/saving.py", line 1018, in load_weights_from_hdf5_group_by_name
> > str(weight_values[i].shape) + '.')
> > **ValueError: Layer #87 (named "sed_with_cATP-DF_atten_0"), weight <tf.Variable 'sed_with_cATP-DF_atten_0/sed_with_cATP-DF_atten_0_kernel:0' shape=(1, 1, 138) dtype=float32_ref> has shape (1, 1, 138), but the saved weight has shape (1, 1, 137)**.
> 
> Previously saved `challenge_results/model_weights/437296/best_model_w.h5`
> I just loaded the model, and I'm embarrassed to see this error.
> 
> I really want to study using this model. I would be grateful if you could help. thank you : )

Were you able to download all the files? It'd be really great if you could provide me some tips to get them Or at least suggest a way by which I can replicate this model using minimal data (minimum files in the train, test, and validation set).

I would just like to make it work without any errors. I'd be really grateful if you could provide some resources explaining this and guide me. Thanks.
