### ISSUE TITLE
[Dataset Acuisition]

### ISSUE THREAD

**Issue by kaiii0328** [Kikyo-16/Sound_event_detection#3]
Hi, May I ask where should can get the wav files listed in /dataset/text/eval-2019.lst file? I have tried to download relevant datasets  such as DESED_synthetic, DESED_public_eval. But the file names in these dataset didn't match in what are listed. Can you help me preprare the dataset and reproduce your DCASE2019-semi results? Thanks!

**Comment by Kikyo-16** [comment]
Since the DESED has been reorganized and they have changed the name of original files, I have no idea of providing the mapping list or the original dataset either.
